/**
 * Recovery channels supported by RevenueAI
 */
export type RecoveryChannel = "EMAIL" | "SMS" | "WHATSAPP" | "PAYMENT_LINK";

/**
 * Event triggers for payment notification dispatches
 */
export type RecoveryEventType = "PAYMENT_FAILED" | "PAYMENT_SUCCESS" | "RECOVERY_LINK";

/**
 * AI Recommendation Priority Urgency
 */
export type RecoveryUrgency = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";

/**
 * Detailed recommendation output generated by the AI reasoning engine
 */
export interface AIRecoveryDecision {
  channel: RecoveryChannel;
  urgency: RecoveryUrgency;
  confidenceScore: number;
  reasoning: string;
  suggestedAction: string;
  recommendedWaitHours?: number;
}

/**
 * Status of a specific recovery dispatch attempt
 */
export type AttemptStatus = "LINK_CREATED" | "DISPATCHED" | "RECOVERED" | "FAILED" | "EXPIRED";

/**
 * Recovery attempt entity representation
 */
export interface RecoveryAttemptRecord {
  id: string;
  customerId: string;
  paymentId: string;
  channel: RecoveryChannel;
  status: AttemptStatus;
  aiReasoning: string | null;
  aiRecommendation: string | null;
  message: string;
  paymentLink: string;
  recoveredAmount: number;
  attemptedAt: Date | string;
  recoveredAt?: Date | string | null;
}
